# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Myra Labs
tagline:             The Blog
description:         The <i>Completely</i> automated assistant you can text.
url:                 http://myralabs.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Myra Labs
  url:               https://twitter.com/myralabs
  email:             hello@myralabs.com

# Custom vars
version:             1.0.0
